// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Surveillance.Infrastructure.Data;

#nullable disable

namespace UPHC.SurveillanceDashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522090849_InitialLMIS")]
    partial class InitialLMIS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.CaseRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressOfPatient")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateReported")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FacilityId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCommunicable")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LabConfirmedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OnsetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("IX_CaseRecords_FacilityId");

                    b.HasIndex("UserId");

                    b.HasIndex("FacilityId", "CreatedDate")
                        .HasDatabaseName("IX_CaseRecords_FacilityId_CreatedDate");

                    b.HasIndex("IsCommunicable", "OnsetDate")
                        .HasDatabaseName("IX_CaseRecords_IsCommunicable_OnsetDate");

                    b.ToTable("CaseRecords");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.CaseRecordLabTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CaseRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("LabTestId")
                        .HasColumnType("integer");

                    b.Property<int?>("LabTestId1")
                        .HasColumnType("integer");

                    b.Property<string>("ReportPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaseRecordId");

                    b.HasIndex("LabTestId");

                    b.HasIndex("LabTestId1");

                    b.HasIndex("SampleId");

                    b.HasIndex("TestedAt");

                    b.ToTable("CaseRecordLabTests");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.CaseRecordSymptom", b =>
                {
                    b.Property<int>("CaseRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("SymptomId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("SymptomId1")
                        .HasColumnType("integer");

                    b.HasKey("CaseRecordId", "SymptomId");

                    b.HasIndex("SymptomId");

                    b.HasIndex("SymptomId1");

                    b.ToTable("CaseRecordSymptoms");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.Disease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsNotifiable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Diseases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsNotifiable = true,
                            Name = "Dengue"
                        },
                        new
                        {
                            Id = 2,
                            IsNotifiable = true,
                            Name = "Malaria"
                        },
                        new
                        {
                            Id = 3,
                            IsNotifiable = true,
                            Name = "Chikungunya"
                        },
                        new
                        {
                            Id = 4,
                            IsNotifiable = true,
                            Name = "COVID-19"
                        },
                        new
                        {
                            Id = 5,
                            IsNotifiable = true,
                            Name = "Influenza"
                        },
                        new
                        {
                            Id = 6,
                            IsNotifiable = true,
                            Name = "Tuberculosis"
                        },
                        new
                        {
                            Id = 7,
                            IsNotifiable = true,
                            Name = "Typhoid"
                        },
                        new
                        {
                            Id = 8,
                            IsNotifiable = true,
                            Name = "Cholera"
                        },
                        new
                        {
                            Id = 9,
                            IsNotifiable = true,
                            Name = "Measles"
                        },
                        new
                        {
                            Id = 10,
                            IsNotifiable = true,
                            Name = "Rubella"
                        },
                        new
                        {
                            Id = 11,
                            IsNotifiable = true,
                            Name = "Meningitis"
                        },
                        new
                        {
                            Id = 12,
                            IsNotifiable = true,
                            Name = "AES/JE"
                        },
                        new
                        {
                            Id = 13,
                            IsNotifiable = true,
                            Name = "Hepatitis B"
                        },
                        new
                        {
                            Id = 14,
                            IsNotifiable = true,
                            Name = "Hepatitis C"
                        },
                        new
                        {
                            Id = 15,
                            IsNotifiable = true,
                            Name = "Leptospirosis"
                        },
                        new
                        {
                            Id = 16,
                            IsNotifiable = true,
                            Name = "Scrub Typhus"
                        },
                        new
                        {
                            Id = 17,
                            IsNotifiable = true,
                            Name = "Rabies"
                        },
                        new
                        {
                            Id = 18,
                            IsNotifiable = true,
                            Name = "Kala-azar"
                        },
                        new
                        {
                            Id = 19,
                            IsNotifiable = true,
                            Name = "Filariasis"
                        },
                        new
                        {
                            Id = 20,
                            IsNotifiable = true,
                            Name = "Leprosy"
                        },
                        new
                        {
                            Id = 21,
                            IsNotifiable = true,
                            Name = "HIV/AIDS"
                        });
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.DiseaseLabTest", b =>
                {
                    b.Property<int>("DiseaseId")
                        .HasColumnType("integer");

                    b.Property<int>("LabTestId")
                        .HasColumnType("integer");

                    b.HasKey("DiseaseId", "LabTestId");

                    b.HasIndex("LabTestId");

                    b.ToTable("DiseaseLabTests");

                    b.HasData(
                        new
                        {
                            DiseaseId = 1,
                            LabTestId = 1
                        },
                        new
                        {
                            DiseaseId = 1,
                            LabTestId = 2
                        },
                        new
                        {
                            DiseaseId = 1,
                            LabTestId = 3
                        },
                        new
                        {
                            DiseaseId = 2,
                            LabTestId = 4
                        },
                        new
                        {
                            DiseaseId = 2,
                            LabTestId = 5
                        },
                        new
                        {
                            DiseaseId = 2,
                            LabTestId = 1
                        },
                        new
                        {
                            DiseaseId = 4,
                            LabTestId = 6
                        },
                        new
                        {
                            DiseaseId = 4,
                            LabTestId = 7
                        },
                        new
                        {
                            DiseaseId = 6,
                            LabTestId = 10
                        },
                        new
                        {
                            DiseaseId = 6,
                            LabTestId = 11
                        },
                        new
                        {
                            DiseaseId = 7,
                            LabTestId = 8
                        },
                        new
                        {
                            DiseaseId = 7,
                            LabTestId = 9
                        },
                        new
                        {
                            DiseaseId = 8,
                            LabTestId = 16
                        },
                        new
                        {
                            DiseaseId = 9,
                            LabTestId = 18
                        },
                        new
                        {
                            DiseaseId = 10,
                            LabTestId = 19
                        },
                        new
                        {
                            DiseaseId = 21,
                            LabTestId = 20
                        });
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.DiseaseSymptom", b =>
                {
                    b.Property<int>("DiseaseId")
                        .HasColumnType("integer");

                    b.Property<int>("SymptomId")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("DiseaseId", "SymptomId");

                    b.HasIndex("SymptomId");

                    b.ToTable("DiseaseSymptoms");

                    b.HasData(
                        new
                        {
                            DiseaseId = 1,
                            SymptomId = 1,
                            Weight = 10
                        },
                        new
                        {
                            DiseaseId = 1,
                            SymptomId = 2,
                            Weight = 8
                        },
                        new
                        {
                            DiseaseId = 1,
                            SymptomId = 8,
                            Weight = 8
                        },
                        new
                        {
                            DiseaseId = 1,
                            SymptomId = 10,
                            Weight = 9
                        },
                        new
                        {
                            DiseaseId = 2,
                            SymptomId = 1,
                            Weight = 10
                        },
                        new
                        {
                            DiseaseId = 2,
                            SymptomId = 24,
                            Weight = 9
                        },
                        new
                        {
                            DiseaseId = 2,
                            SymptomId = 22,
                            Weight = 7
                        },
                        new
                        {
                            DiseaseId = 4,
                            SymptomId = 1,
                            Weight = 8
                        },
                        new
                        {
                            DiseaseId = 4,
                            SymptomId = 6,
                            Weight = 10
                        },
                        new
                        {
                            DiseaseId = 4,
                            SymptomId = 7,
                            Weight = 10
                        },
                        new
                        {
                            DiseaseId = 4,
                            SymptomId = 22,
                            Weight = 7
                        },
                        new
                        {
                            DiseaseId = 6,
                            SymptomId = 6,
                            Weight = 10
                        },
                        new
                        {
                            DiseaseId = 6,
                            SymptomId = 16,
                            Weight = 10
                        },
                        new
                        {
                            DiseaseId = 6,
                            SymptomId = 17,
                            Weight = 9
                        },
                        new
                        {
                            DiseaseId = 8,
                            SymptomId = 5,
                            Weight = 10
                        },
                        new
                        {
                            DiseaseId = 8,
                            SymptomId = 4,
                            Weight = 8
                        },
                        new
                        {
                            DiseaseId = 9,
                            SymptomId = 1,
                            Weight = 7
                        },
                        new
                        {
                            DiseaseId = 9,
                            SymptomId = 3,
                            Weight = 10
                        },
                        new
                        {
                            DiseaseId = 9,
                            SymptomId = 6,
                            Weight = 7
                        },
                        new
                        {
                            DiseaseId = 13,
                            SymptomId = 11,
                            Weight = 10
                        },
                        new
                        {
                            DiseaseId = 13,
                            SymptomId = 12,
                            Weight = 7
                        },
                        new
                        {
                            DiseaseId = 13,
                            SymptomId = 22,
                            Weight = 6
                        });
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FacilityAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacilityAddress = "Unit-4",
                            FacilityName = "UCHC Unit-4",
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            FacilityAddress = "Dumduma",
                            FacilityName = "UCHC Dumduma",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            FacilityAddress = "Unit-8",
                            FacilityName = "UCHC Unit-8",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            FacilityAddress = "Old Town,Lingaraj nagar",
                            FacilityName = "UCHC BMC Hospital",
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            FacilityAddress = "Kharvela Nagar",
                            FacilityName = "Unit-3 UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            FacilityAddress = "Unit-4,Near AG Colony",
                            FacilityName = "Unit-4 UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            FacilityAddress = "Unit-8",
                            FacilityName = "Unit-8 UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            FacilityAddress = "Unit-9 Industrial Colony",
                            FacilityName = "Unit-9 UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            FacilityAddress = "Saheed Nagar",
                            FacilityName = "Saheed Nagar UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            FacilityAddress = "Satya Nagar,Near Kali Mandir",
                            FacilityName = "Satya Nagar UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            FacilityAddress = "Rental Colony, IRC Village",
                            FacilityName = "Baramunda UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            FacilityAddress = "IRC Village, Nayapalli",
                            FacilityName = "IRC Village UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            FacilityAddress = "GGP Colony, Rasulgarh",
                            FacilityName = "Rasulgarh UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            FacilityAddress = "Gadeswar,Near RI Office Kalarahanga",
                            FacilityName = "Gadakan UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            FacilityAddress = "Pokhariput,Ward No-62",
                            FacilityName = "Pokhariput UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            FacilityAddress = "CS Pur HB Colony,Ward No-8",
                            FacilityName = "Chandrasekharpur UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            FacilityAddress = "Niladri Vihar, Sector-I",
                            FacilityName = "Niladri Vihar UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 18,
                            FacilityAddress = "BJB Nagar,Near BJB Nagar Hata",
                            FacilityName = "Bjb Nagar UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            FacilityAddress = "Bhimatangi Housing Board area",
                            FacilityName = "Bhimatangi UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            FacilityAddress = "Kapilaprasad Village area",
                            FacilityName = "Kapilaprasad UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            FacilityAddress = "Badagada Village,Brit area",
                            FacilityName = "Badagada UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            FacilityAddress = "Jharapada Village area",
                            FacilityName = "Jharapada UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            FacilityAddress = "Bharatpur Slum,Mahalaxmi Vihar",
                            FacilityName = "Bharatpur UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            FacilityAddress = "Patia Village,Damana area",
                            FacilityName = "Patia UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            FacilityAddress = "VSS Nagar Housing Board area",
                            FacilityName = "VSS Nagar UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            FacilityAddress = "Laxmisagar Village area",
                            FacilityName = "Laxmisagar UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            FacilityAddress = "Ward 12, near Kalyan Mandap",
                            FacilityName = "VSS Nagar UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 28,
                            FacilityAddress = "Ward 14, Sector 1",
                            FacilityName = "Niladri Vihar UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 29,
                            FacilityAddress = "Ward 59, near Samantarapur Square",
                            FacilityName = "Samantarapur UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 30,
                            FacilityAddress = "Ward 49, Shreekhetra Vihar",
                            FacilityName = "Aiginia UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 31,
                            FacilityAddress = "Ward 65, Kalinga Vihar K-9",
                            FacilityName = "Patrapada UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 32,
                            FacilityAddress = "L170, Baramunda Housing Board Colony",
                            FacilityName = "Baramunda HB UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 33,
                            FacilityAddress = "Satya Vihar, Ward 5",
                            FacilityName = "Chakaisiani UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 34,
                            FacilityAddress = "Acharya Vihar, Ward 27",
                            FacilityName = "Acharya Vihar UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 35,
                            FacilityAddress = "Kalarahanga, near KIIT area",
                            FacilityName = "Kalarahanga UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 36,
                            FacilityAddress = "Sainik School Road, Ward 5",
                            FacilityName = "Palasuni UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 37,
                            FacilityAddress = "Subudhipur, Aiginia area",
                            FacilityName = "Subudhipur UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 38,
                            FacilityAddress = "Badagada Brit Colony",
                            FacilityName = "Badagada Sabarasahi UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 39,
                            FacilityAddress = "Hanspal, Balianta area",
                            FacilityName = "Hanspal UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 40,
                            FacilityAddress = "Gadakana area, Ward 9",
                            FacilityName = "Gadakana UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 41,
                            FacilityAddress = "Jharapada, near Jail area",
                            FacilityName = "Jharapada UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 42,
                            FacilityAddress = "Sailashree Vihar, Ward 7",
                            FacilityName = "Sailashree Vihar UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 43,
                            FacilityAddress = "Unit-6 area, Ward 46",
                            FacilityName = "Unit-6 UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 44,
                            FacilityAddress = "Dumuduma Housing Board Phase-III",
                            FacilityName = "Dumuduma UHWC",
                            Type = 4
                        });
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.FacilityReferral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CHCId")
                        .HasColumnType("integer");

                    b.Property<int>("UPHCId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CHCId");

                    b.HasIndex("UPHCId", "CHCId")
                        .IsUnique();

                    b.ToTable("FacilityReferrals", t =>
                        {
                            t.HasCheckConstraint("CK_NoSelfReferral", "\"UPHCId\" <> \"CHCId\"");
                        });
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.LabResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseRecordLabTestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnteredByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ResultStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ResultValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("VerifiedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CaseRecordLabTestId");

                    b.HasIndex("EnteredAt");

                    b.HasIndex("IsVerified");

                    b.HasIndex("ResultStatus");

                    b.ToTable("LabResults");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.LabTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LabTests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CBC"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dengue NS1"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dengue IgM"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Peripheral Smear"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Malaria Antigen"
                        },
                        new
                        {
                            Id = 6,
                            Name = "RTPCR"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Rapid Antigen Test"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Widal Test"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Blood Culture"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Sputum AFB"
                        },
                        new
                        {
                            Id = 11,
                            Name = "CBNAAT"
                        },
                        new
                        {
                            Id = 12,
                            Name = "CSF Analysis"
                        },
                        new
                        {
                            Id = 13,
                            Name = "ELISA"
                        },
                        new
                        {
                            Id = 14,
                            Name = "LFT"
                        },
                        new
                        {
                            Id = 15,
                            Name = "KFT"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Stool Culture"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Urine Routine"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Measles IgM"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Rubella IgM"
                        },
                        new
                        {
                            Id = 20,
                            Name = "HIV ELISA"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Hepatitis B Surface Antigen"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Hepatitis C Antibody"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Leptospira IgM"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Scrub Typhus IgM"
                        },
                        new
                        {
                            Id = 25,
                            Name = "JE IgM ELISA"
                        });
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.LabTestSampleType", b =>
                {
                    b.Property<int>("LabTestId")
                        .HasColumnType("integer");

                    b.Property<int>("SampleTypeId")
                        .HasColumnType("integer");

                    b.HasKey("LabTestId", "SampleTypeId");

                    b.HasIndex("SampleTypeId");

                    b.ToTable("LabTestSampleTypes");

                    b.HasData(
                        new
                        {
                            LabTestId = 1,
                            SampleTypeId = 1
                        },
                        new
                        {
                            LabTestId = 2,
                            SampleTypeId = 2
                        },
                        new
                        {
                            LabTestId = 3,
                            SampleTypeId = 2
                        },
                        new
                        {
                            LabTestId = 4,
                            SampleTypeId = 1
                        },
                        new
                        {
                            LabTestId = 5,
                            SampleTypeId = 1
                        },
                        new
                        {
                            LabTestId = 6,
                            SampleTypeId = 5
                        },
                        new
                        {
                            LabTestId = 7,
                            SampleTypeId = 5
                        },
                        new
                        {
                            LabTestId = 8,
                            SampleTypeId = 1
                        },
                        new
                        {
                            LabTestId = 9,
                            SampleTypeId = 1
                        },
                        new
                        {
                            LabTestId = 10,
                            SampleTypeId = 7
                        },
                        new
                        {
                            LabTestId = 11,
                            SampleTypeId = 7
                        },
                        new
                        {
                            LabTestId = 12,
                            SampleTypeId = 6
                        },
                        new
                        {
                            LabTestId = 13,
                            SampleTypeId = 2
                        },
                        new
                        {
                            LabTestId = 14,
                            SampleTypeId = 1
                        },
                        new
                        {
                            LabTestId = 15,
                            SampleTypeId = 1
                        },
                        new
                        {
                            LabTestId = 16,
                            SampleTypeId = 4
                        },
                        new
                        {
                            LabTestId = 17,
                            SampleTypeId = 3
                        },
                        new
                        {
                            LabTestId = 18,
                            SampleTypeId = 2
                        },
                        new
                        {
                            LabTestId = 19,
                            SampleTypeId = 2
                        },
                        new
                        {
                            LabTestId = 20,
                            SampleTypeId = 2
                        },
                        new
                        {
                            LabTestId = 21,
                            SampleTypeId = 2
                        },
                        new
                        {
                            LabTestId = 22,
                            SampleTypeId = 2
                        },
                        new
                        {
                            LabTestId = 23,
                            SampleTypeId = 2
                        },
                        new
                        {
                            LabTestId = 24,
                            SampleTypeId = 2
                        },
                        new
                        {
                            LabTestId = 25,
                            SampleTypeId = 2
                        });
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FacilityId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CaseRecordId", "Type")
                        .IsUnique()
                        .HasDatabaseName("IX_Notifications_CaseRecordId_Type");

                    b.HasIndex("FacilityId", "Timestamp")
                        .HasDatabaseName("IX_Notifications_FacilityId_Timestamp");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CaseRecordId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CollectedBy")
                        .HasColumnType("text");

                    b.Property<string>("CollectionNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DispatchReferenceNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProcessingFacilityId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReceivedAtLabAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SampleTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("CaseRecordId");

                    b.HasIndex("CollectedAt");

                    b.HasIndex("ProcessingFacilityId");

                    b.HasIndex("SampleTypeId");

                    b.HasIndex("Status");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.SampleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SampleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Blood"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Serum"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Urine"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Stool"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Swab"
                        },
                        new
                        {
                            Id = 6,
                            Name = "CSF"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sputum"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Skin Scraping"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Biopsy"
                        });
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.Symptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Symptoms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fever"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Headache"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rash"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Vomiting"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Diarrhea"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cough"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Breathlessness"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Body Pain"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Joint Pain"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bleeding"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Jaundice"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Abdominal Pain"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Neck Rigidity"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Seizure"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Paralysis"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Weight Loss"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Night Sweats"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Lymph Node Swelling"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Skin Lesions"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Sore Throat"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Conjunctivitis"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Fatigue"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Loss of Appetite"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Chills"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Chest Pain"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Surveillance.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Surveillance.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Surveillance.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Surveillance.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Surveillance.Domain.Entities.Facility", "Facility")
                        .WithMany("Users")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.CaseRecord", b =>
                {
                    b.HasOne("Surveillance.Domain.Entities.Facility", "Facility")
                        .WithMany("CaseRecords")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Surveillance.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.CaseRecordLabTest", b =>
                {
                    b.HasOne("Surveillance.Domain.Entities.CaseRecord", "CaseRecord")
                        .WithMany("LabTests")
                        .HasForeignKey("CaseRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Surveillance.Domain.Entities.LabTest", "LabTest")
                        .WithMany()
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Surveillance.Domain.Entities.LabTest", null)
                        .WithMany("CaseRecordLabTests")
                        .HasForeignKey("LabTestId1");

                    b.HasOne("Surveillance.Domain.Entities.Sample", "Sample")
                        .WithMany("LabTests")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("CaseRecord");

                    b.Navigation("LabTest");

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.CaseRecordSymptom", b =>
                {
                    b.HasOne("Surveillance.Domain.Entities.CaseRecord", "CaseRecord")
                        .WithMany("CaseRecordSymptoms")
                        .HasForeignKey("CaseRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Surveillance.Domain.Entities.Symptom", "Symptom")
                        .WithMany()
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Surveillance.Domain.Entities.Symptom", null)
                        .WithMany("CaseRecordSymptoms")
                        .HasForeignKey("SymptomId1");

                    b.Navigation("CaseRecord");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.DiseaseLabTest", b =>
                {
                    b.HasOne("Surveillance.Domain.Entities.Disease", "Disease")
                        .WithMany("DiseaseLabTests")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Surveillance.Domain.Entities.LabTest", "LabTest")
                        .WithMany("DiseaseLabTests")
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("LabTest");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.DiseaseSymptom", b =>
                {
                    b.HasOne("Surveillance.Domain.Entities.Disease", "Disease")
                        .WithMany("DiseaseSymptoms")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Surveillance.Domain.Entities.Symptom", "Symptom")
                        .WithMany("DiseaseSymptoms")
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.FacilityReferral", b =>
                {
                    b.HasOne("Surveillance.Domain.Entities.Facility", "CHC")
                        .WithMany("CHCReferrals")
                        .HasForeignKey("CHCId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Surveillance.Domain.Entities.Facility", "UPHC")
                        .WithMany("UPHCReferrals")
                        .HasForeignKey("UPHCId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CHC");

                    b.Navigation("UPHC");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.LabResult", b =>
                {
                    b.HasOne("Surveillance.Domain.Entities.CaseRecordLabTest", "CaseRecordLabTest")
                        .WithMany("LabResults")
                        .HasForeignKey("CaseRecordLabTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseRecordLabTest");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.LabTestSampleType", b =>
                {
                    b.HasOne("Surveillance.Domain.Entities.LabTest", "LabTest")
                        .WithMany("LabTestSampleTypes")
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Surveillance.Domain.Entities.SampleType", "SampleType")
                        .WithMany("LabTestSampleTypes")
                        .HasForeignKey("SampleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabTest");

                    b.Navigation("SampleType");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Surveillance.Domain.Entities.CaseRecord", "CaseRecord")
                        .WithMany("Notifications")
                        .HasForeignKey("CaseRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Surveillance.Domain.Entities.Facility", "Facility")
                        .WithMany("Notifications")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaseRecord");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.Sample", b =>
                {
                    b.HasOne("Surveillance.Domain.Entities.CaseRecord", "CaseRecord")
                        .WithMany("Samples")
                        .HasForeignKey("CaseRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Surveillance.Domain.Entities.Facility", "ProcessingFacility")
                        .WithMany()
                        .HasForeignKey("ProcessingFacilityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Surveillance.Domain.Entities.SampleType", "SampleType")
                        .WithMany()
                        .HasForeignKey("SampleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaseRecord");

                    b.Navigation("ProcessingFacility");

                    b.Navigation("SampleType");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.CaseRecord", b =>
                {
                    b.Navigation("CaseRecordSymptoms");

                    b.Navigation("LabTests");

                    b.Navigation("Notifications");

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.CaseRecordLabTest", b =>
                {
                    b.Navigation("LabResults");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.Disease", b =>
                {
                    b.Navigation("DiseaseLabTests");

                    b.Navigation("DiseaseSymptoms");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.Facility", b =>
                {
                    b.Navigation("CHCReferrals");

                    b.Navigation("CaseRecords");

                    b.Navigation("Notifications");

                    b.Navigation("UPHCReferrals");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.LabTest", b =>
                {
                    b.Navigation("CaseRecordLabTests");

                    b.Navigation("DiseaseLabTests");

                    b.Navigation("LabTestSampleTypes");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.Sample", b =>
                {
                    b.Navigation("LabTests");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.SampleType", b =>
                {
                    b.Navigation("LabTestSampleTypes");
                });

            modelBuilder.Entity("Surveillance.Domain.Entities.Symptom", b =>
                {
                    b.Navigation("CaseRecordSymptoms");

                    b.Navigation("DiseaseSymptoms");
                });
#pragma warning restore 612, 618
        }
    }
}
